on:
  schedule:
    - cron: 0 0 * * *
jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: サブモジュールの最新リリースをcheckout
        run: |
          cd gcd/
          git checkout main
          git checkout $(git describe --tags --abbrev=0)
      - uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: submoduleの更新
          branch: update-submodule
          title: submoduleの更新
          body: ""